### PR TITLE
Fix wrong parameter values for /search in README

### PR DESCRIPTION
**Pull request by SiC42**
The API expects the category to be written in all uppercase. This should be reflected in the README

### CODE REVIEW

**Comment by prasanthhs** [comment]
@SiC42 I think both caps and small is supported from code. Check setCategory function inside SearchRequest.java. Both Entity and ENTITY are OK, Similarly Property and PROPERTY , CLASS and Class.

**Comment by SiC42** [comment]
@prasanthhs You are right, both all lower and all upper case are supported.
However, UpperCamelCase is not, but that is what the README says...

**Comment by prasanthhs** [comment]
@SiC42 Ya ..I will add it to code as a part of next release.I missed that case. I think supporting all 3 values is better.

**Comment by SiC42** [comment]
@prasanthhs that is also a solution. Proceed with this branch as you wish

**Pull request merged**
